name: Workflow Example

on:
  push:
    branches:
      - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Decir hola
              run: echo "Hola, mundo!"

            - name: Decir adios
              run: echo ADIOS
            - name: Notificar despliegue a la API
              run: |
                curl -X POST -H "Content-Type: application/json" \
                -d '{"action": "completed"}' \
                https://92fb-2806-262-3404-5fa-b5ac-c022-3351-f0de.ngrok-free.app/webhook
