name: Workflow Example

on:
  push:
    branches:
      - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Decir hola
              run: echo "Hola, mundo!"

            - name: Decir adios
              run: echo ADIOS
            - name: Notificar despliegue a la API
              run: |
                curl -X POST -H "Content-Type: application/json" \
                -d '{"action": "completed"}' \
                http://localhost:8080/webhook
